server:
  port: 80
eureka:  client:    register-with-eureka: false # false 表示不将自己注册进eureka
    service-url:      defaultZone: http://eureka7001.com:7001/eureka/,http://eureka7002.com:7002/eureka/,http://eureka7003.com:7003/eureka/
      