server:
  port: 7001
eureka:  instance:    hostname: eureka7001.com # 服务端实例名称
  client:    register-with-eureka: false # false 表示不向服务中心注册自己
    fetch-registry: false
    service-url:      defaultZone: http://eureka7003.com:7003/,http://eureka7002.com:7002/
