server:
  port: 8002
mybatis:
  config-location: classpath:mybatis/mybatis.cfg.xml
  mapper-locations:
  - classpath:mybatis/mapper/**/*.xml
spring:
  application:
    name: cloud-provider-dept
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    url: jdbc:mysql://localhost:3306/clouddb02
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
    dbcp2:
      min-idle: 3
      max-total: 8
      initial-size: 8
      max-wait-millis: 200
eureka:
  client:
    service-url: 
      defaultZone: http://eureka7003.com:7003/eureka/,http://eureka7002.com:7002/eureka/,http://eureka7001.com:7001/eureka/
  instance:
    instance-id: cloud-provider-dept-8002
    prefer-ip-address: true
info:
  app.name: cloud-dept-provider-8002
  company.name: www.cloud.com
  build.artifactId: cloud-provider-8002
  build.version: 0.0.1-SNAPSHOT